
DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"name" character varying(100),
"score" integer
);

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO hangman_user;

REVOKE ALL ON users FROM public;
GRANT ALL ON users TO hangman_user;

